### ISSUE TITLE
Overworld: Sign in Merina City can be read from behind

### ISSUE THREAD

**Issue by SBird1337** [pokemon-violet/Violet#4]
![grafik](https://user-images.githubusercontent.com/3799173/77866866-002cf180-7235-11ea-9906-c4602fe3d01e.png)

**Comment by dfuchsgruber** [comment]
![grafik](https://user-images.githubusercontent.com/13219625/77969166-68d5a600-72e9-11ea-93a3-e0f3a5f5b200.png)
